### ISSUE TITLE
MG 4 2023 EH32 X7 Windows open

### ISSUE THREAD

**Issue by Soodium** [ad-ha/mg-saic-ha#18]
Hello everyone. With the update to version 0.4.2, the battery level display is finally working. However, I can’t explain why it shows 102% the battery is 100% charged. But I noticed that the windows are shown as open, even though they’re all closed.

![Screenshot 2024-11-08 074414](https://github.com/user-attachments/assets/22cba89d-d655-4fd9-8f73-c2e150c5d399)

**Comment by ad-ha** [comment]
Hi @Soodium

Glad that it is mostly working for you.

So that seems to be the "magic" of MG API, that sometimes sends "generic" data instead of correct data.

I catches several generic responses that appear on my vehicle, but the 102% battery did not happen. Let me have a look and I will add additional exceptions to discard those kind of responses. 

The windows probably is the same issue. The API sometimes sends cache data, seems that not always real-time.

Thanks for the feedback.

**Comment by ad-ha** [comment]
See comment on #19
