### ISSUE TITLE
Charging current, voltage, power way off expected values

### ISSUE THREAD

**Issue by BikeMikeAU** [ad-ha/mg-saic-ha#33]
I have MG ZS EV connected and returning data successfully since 0.4.7 added Australian server. Thanks!
However the charge values are off. Using a granny charger I get 230V, 20A, 4.6kW when it should be somewhere around 400V, 4A, 1.6kW. I see there are conversion factors in const.py but are these expected to be set differently for different vehicles?

**Comment by BikeMikeAU** [comment]
Seems like CHARGING_VOLTAGE_FACTOR = 0.250 is about right, this is a nice round value.
But CHARGING_CURRENT_FACTOR = 0.000168 is the value needed based on my tests.
I'm basing this on comparison with the values returned by the SAIC MQTT integration, which I have also installed. A google search indicates ~400V is correct, and the current/power look right based on measured power input to the charger and about 90% efficiency.

**Comment by ad-ha** [comment]
Thanks @BikeMikeAU

So I based those convertion rates on what I saw on my Marvel R. And, somehow, those are not entirely correct the whole time, because on different charges, using the same charger, the vehicle shows different data (even if the charger output is the same).

I still did not figure entirely what's going on with that. Using the MQTT values did not work either, which would translate into voltages of a ~100V, which do not exist in Europe.

I really don't get yet what's MG doing with those figures.

I will accept any ideas or help, so we may get this to work properly.

**Comment by BikeMikeAU** [comment]
I have a 7kW charger coming so will see how it looks with that one. So far it looks consistent with the small charger. I'm confident that 0.250 gives me correct voltage but need to confirm the current. I've settled on 0.00015 for now.

**Comment by ad-ha** [comment]
Hi @BikeMikeAU 

Again, those constants, right now, make sense on my integration, but sometimes seems like their are slightly off. Just don't know exactly the reason behind that on the data from MG.

**Comment by Jamiro75** [comment]
For me,Mg4 2023  "EH32 X7" , the "Charging Power", and the "Charging Current" seems are double, the other more or less is ok
great job for the rest
many thanks

**Comment by ad-ha** [comment]
> For me,Mg4 2023  "EH32 X7" , the "Charging Power", and the "Charging Current" seems are double, the other more or less is ok

@Jamiro75 Thank you for the feedback. Although, I seem to not find a balance between what each vehicle is reporting.

**Comment by ad-ha** [comment]
Hi,

Going through this and looking into the MQTT integration, mentioned by @BikeMikeAU , I am struggling to find a way to get this working.

The MQTT integration gets the data from 2 data values on the charging dictionary:
- Current: conditional of `bmsPackCrntV` different than 0 and calculation based on  `bmsPackCrnt`
- Voltage: `bmsPackVol`

In my case, with the log from a current charging process, I get these values:
```
bmsPackCrntV=None
bmsPackCrnt=19795
bmsPackVol=1449
```

Looking into my actual factors, since 0.6.0, this would translate into:
```
# Conversion factors for charging data
CHARGING_CURRENT_FACTOR = 0.00095
CHARGING_VOLTAGE_FACTOR = 0.151
```

- Voltage: 218.80 V
- Current: 18.81 A
- Power: 4.12 kW

Which is very similar to the values I am getting on the charger.

Can any of you share your data, on a charging process, for these fields (including the vehicle model) for comparison?

Cheers

**Comment by ad-ha** [comment]
Hi @BikeMikeAU 

Thanks a lot for the feedback and input. 

I may be wrong, but I understand that these sensors are meant to be showing the input data from the grid, correctly? I am using an AC charger at home and my grid voltage is 220V-230V, that's why this makes a bit sense to me. But again, I might be seeing this wrong and it should be about the car battery voltage.

Please share the data that you may get with your home charger and see if we can get somewhere with broader information.

Cheers

**Comment by BikeMikeAU** [comment]
Ok I just did a couple of tests at various grid input currents on my charger, nominally 7A, 15A and 25A. 
The strange thing is, current (and therefore power) reported by mg-saic-ha did not change at all. With a factor of 0.0005 it reports almost constant 9.8 - 9.9A. It seems like the MG API value being used for current is the wrong one?

![image](https://github.com/user-attachments/assets/1d2d286e-102d-4c61-8716-27f90127ef46)

**Comment by ad-ha** [comment]
Looking into the MQTT integration, they look into the Voltage and Current on `onBdChrgrAltrCrntInptVol` and `onBdChrgrAltrCrntInptCrnt` which in my vehicle always return as None:

```
onBdChrgrAltrCrntInptCrnt=None, 
onBdChrgrAltrCrntInptVol=None
```

That's why when implementing this I did not even check on those datasets.

**Comment by BikeMikeAU** [comment]
I found this page https://github.com/SAIC-iSmart-API/documentation
Right at the bottom this formula: current power usage (kW): (bmsPackCrnt * 0.05 - 1000.0) * (bmsPackVol * 0.25) / 1000.0

So current factor must be 0.05 and then subtract 1000. This gives the correct (negative) current. And 0.25 is correct for voltage factor.

**Comment by ad-ha** [comment]
> I found this page https://github.com/SAIC-iSmart-API/documentation Right at the bottom this formula: current power usage (kW): (bmsPackCrnt * 0.05 - 1000.0) * (bmsPackVol * 0.25) / 1000.0
> 
> So current factor must be 0.05 and **then subtract 1000**. This gives the correct (negative) current. And 0.25 is correct for voltage factor.

I know. Check my edited comment above https://github.com/ad-ha/mg-saic-ha/issues/33#issuecomment-2497935854

**Comment by ad-ha** [comment]
It now starts to make a bit more sense to me. Before I was understanding this as input sensors, rather than onboard charging data sensor.

If you can also cross check those current factors from the SAIC-iSmart-API, I will get those addressed for an updated version.

**Comment by BikeMikeAU** [comment]
I will change the factor and adjust code for the -1000 tomorrow and re-test, i'm pretty sure that will fix it.

**Comment by ad-ha** [comment]
> I will change the factor and adjust code for the -1000 tomorrow and re-test, i'm pretty sure that will fix it.

You don't need to change the code. Just check the values on the debug log and do the calculations manually. Might be easier to manage 😄 

Thank you again for your help 👍

**Comment by SquidgyG** [comment]
Came here to report same issue (MG4 Essence 64 in Australia) but looks like you might have figured out the problem!

**Comment by BikeMikeAU** [comment]
It works!
I recorded raw value for current, then applied the formula x 0.05 - 1000
Then calculated V x A = W
However I would prefer to see A and W as positive values, x -0.05 + 1000

![image](https://github.com/user-attachments/assets/f2cea6e9-edae-4216-a8f6-364ed225ad7a)

**Comment by ad-ha** [comment]
Thanks @BikeMikeAU 

I will have a look in a while and do a new release. Let me try it and I will move it after.

Cheers
