### ISSUE TITLE
[REQ] Support charge limit

### ISSUE THREAD

**Issue by nicois** [ad-ha/mg-saic-ha#66]
### Is your feature request related to a problem?

- [ ] Yes

### Please describe the problem

The SAIC API supports controlling the charge limiter current, in Amps (6/8/16/∞).
It would be really good to have this exposed to HA, as it would allow more fine-grained control of the rate of charging, when adapting to variable solar input, for example.

### Describe the solution you'd like

I have created a PR with a partial implementation of the solution. It results in a second `number` being defined with limited values, similar to the `target SOC` number.
https://github.com/ad-ha/mg-saic-ha/pull/65

### Additional context

One complication, as mentioned in the PR, is that the SAIC API needs to be passed both `target SOC` and `charge limit` together; the endpoint cannot be given just one value. This means the two number objects need to be somehow combined. I have half-implemented a solution but it's a bit ugly and I would like feedback before continuing (perhaps by using a weakref from one to the other); I suspect there is a cleaner solution (e.g. a single entity with multiple value somehow?)

**Comment by ad-ha** [comment]
Duplicated #58 

Hi @nicois 

I appreciate the comment and the PR. 

As mentioned here https://github.com/ad-ha/mg-saic-ha/issues/58#issuecomment-2530851654 I already have that developed for the next release.

Instead of using a number, I created a new select entity that allows to select the current limit from a dropdown menu.

I will revise your PR anyhow and check against my actual code to see if there's something that I might have missed. 

I am wondering that you tried your implementation on your vehicle and that it is working fine, right?

Cheers

**Comment by nicois** [comment]
Oh, I should have looked more carefully at what you had already done.

Perhaps using the SAIC package's enums could be worth doing, if you're not already. 

Yes, I have patched my own HA and it's working fine. I don't like how I'm handling the unlimited option by making it 99; hopefully your approach is cleaner.

If I can help with this in some way let me know.

**Comment by ad-ha** [comment]
Hi @nicois 

I just pushed the release 0.8.0. The whole code is already updated on main and the release ready to update on HACS.

Give it a try and let me know if there's something that I may have missed.

Cheers
