### ISSUE TITLE
[ISSUE] MG4 GPS Co-ordinates - Zero Value?

### ISSUE THREAD

**Issue by ad-ha** [ad-ha/mg-saic-ha#70]
### Discussed in https://github.com/ad-ha/mg-saic-ha/discussions/62

<div type='discussions-op-text'>

<sup>Originally posted by **thompct0** December 11, 2024</sup>
Hi - firstly, great work with the integration, thank you!

Question... the GPS Location reported when the MG4 is powered on (i.e. Driving) is reported ok and Home Assistant locates it correctly as per the zones defined.  Looks like when the car is "off" though that any update, triggered by a manual update of vehicle data,  to the GPS location is then Zero'd out (Assume the car has powered down and is not reporting anything?).

Can you replicate this or just me? :-)

![image](https://github.com/user-attachments/assets/2855ce3b-27bd-4cba-91da-44da18fb5a6a)
![image](https://github.com/user-attachments/assets/14a1bc45-e02b-4d12-ab73-0facc23cbf39)

</div>

Create new generic response handling for _null_ GPS details.

**Comment by xenionscorp** [comment]
I have an "MG5 Electric" and i had this issue too when first installed this integration, or it showed correctly until the first update after the car was used.
A couple hours later the whole car and all its entities went "unavailable".
Then i upgraded some other HA components that required reboot, so i did that reboot, and since that this issue went away for me. 
My only "issue" with the GPS tracking is that earlier i used the MQTT based integration, and then the GPS location was updated like once every 5 second, now (0.7.2) Its tied to the update schedule, once per hour.
